### ISSUE TITLE
No release available for Composer

### ISSUE THREAD

**Issue by calcinai** [XeroAPI/xero-php-sample-app#3]
Currently we get this on `composer create-project`:

```
  [InvalidArgumentException]                                              
  Could not find package xero/xero-php-sample-app with stability stable.  
```

This can be resolved by releasing a commit with a tag, say `1.0.0`.  It will then be seen as stable by composer.  It'd be good to do this after merging #2, so it includes all the changes there.

**Comment by SidneyAllen** [comment]
Merged PR #2 and did release 1.0.0.  - Thanks for your help with this project!
