### ISSUE TITLE
Not Found Issue

### ISSUE THREAD

**Issue by vineetdikonia** [XeroAPI/xero-php-sample-app#7]
Hello everyone,
I am setup this repo and configure all the credentials but facing the attached issue. Is someone here who can let me know what's the wrong at my end or is something need to fix at code?
![xerophp sample application an exception has occurred 2018-10-04 11-33-29](https://user-images.githubusercontent.com/13980482/46456530-d5431800-c7cc-11e8-8912-d2da47df26e3.png)

**Comment by alan-cooney** [comment]
Did you ever fix this @vineetdikonia ?

**Comment by calcinai** [comment]
@vineetdikonia @alan-cooney What was the URL that you got that message on?

**Comment by alan-cooney** [comment]
Sorry @calcinai - I can't reproduce this again now!

**Comment by calcinai** [comment]
Hah ok, @SidneyAllen maybe this can be closed?
